spring.datasource.url=${LEGACYPAY_DB_URL:jdbc:postgresql://localhost:5432/legacypay}
spring.datasource.username=${LEGACYPAY_DB_USERNAME:legacypay}
spring.datasource.password=${LEGACYPAY_DB_PASSWORD:legacypay}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
