CREATE TABLE payment_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_account VARCHAR(50) NOT NULL,
    receiver_account VARCHAR(50) NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    status VARCHAR(50) NOT NULL,
    lifecycle_status VARCHAR(50) NOT NULL,
    idempotency_key VARCHAR(255) UNIQUE,
    reason VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_payment_transactions_created_at
    ON payment_transactions (created_at);

CREATE INDEX idx_payment_transactions_sender_account
    ON payment_transactions (sender_account);
