CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(100) NOT NULL,
    payment_transaction_id BIGINT,
    message VARCHAR(500) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_audit_logs_payment_transaction_id
    ON audit_logs (payment_transaction_id);

CREATE INDEX idx_audit_logs_created_at
    ON audit_logs (created_at);
